# Generated by Django 3.1 on 2022-03-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiaDiem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_dia_diem', models.CharField(max_length=50, unique=True)),
                ('thanh_pho', models.CharField(max_length=50, unique=True)),
                ('gioi_thieu', models.TextField(blank=True, max_length=255)),
                ('hinh_anh1', models.ImageField(blank=True, upload_to='photos/diadiem')),
                ('hinh_anh2', models.ImageField(blank=True, upload_to='photos/diadiem')),
                ('hinh_anh3', models.ImageField(blank=True, upload_to='photos/diadiem')),
                ('ghi_chu', models.TextField(blank=True, max_length=255)),
            ],
        ),
    ]
